"use strict";

var items = [
	{name: 'mocha', 			desc: 'simple, flexible, fun test framework'},
	{name: 'coffee-script', 	desc: 'Unfancy JavaScript'},
	{name: 'uglify-js', 		desc: 'JavaScript parser, mangler/compressor and beautifier toolkit'},
	{name: 'underscore', 		desc: 'JavaScript\'s functional programming helper library.'},
	{name: 'request', 			desc: 'Simplified HTTP request client.'},
	{name: 'async', 			desc: 'Higher-order functions and common patterns for asynchronous code'},
	{name: 'jade', 				desc: 'Jade template engine.'},
	{name: 'optimist', 			desc: 'Light-weight option parsing with an argv hash. No optstrings attached.'},
	{name: 'connect', 			desc: 'High performance middleware framework'},
	{name: 'commander', 		desc: 'the complete solution for node.js command-line programs'},
	{name: 'tap', 				desc: 'A Test-Anything-Protocol library'},
	{name: 'should', 			desc: 'test framework agnostic BDD-style assertions'},
	{name: 'express', 			desc: 'Sinatra inspired web development framework'},
	{name: 'mkdirp', 			desc: 'Recursively mkdir, like `mkdir -p`'},
	{name: 'nodeunit', 			desc: 'Easy unit testing for node.js and the browser.'},
	{name: 'npm', 				desc: 'A package manager for node'},
	{name: 'socket.io', 		desc: 'Real-time apps made cross-browser & easy with a WebSocket-like API'},
	{name: 'mongodb', 			desc: 'A node.js driver for MongoDB'},
	{name: 'stylus', 			desc: 'Robust, expressive, and feature-rich CSS superset'},
	{name: 'mongoose', 			desc: 'Mongoose MongoDB ODM'},
	{name: 'redis', 			desc: 'Redis client library'},
	{name: 'socket.io-client', 	desc: 'Socket.IO client for the browser and node.js'},
	{name: 'nodemon', 			desc: 'Simple monitor script for use during development of a node.js app.'},
	{name: 'jsdom', 			desc: 'A JavaScript implementation of the W3C DOM'},
	{name: 'lodash', 			desc: 'The modern build of lodash modular utilities.'},
	{name: 'bower', 			desc: 'The browser package manager'},
	{name: 'grunt', 			desc: 'The JavaScript Task Runner'},
	{name: 'gulp', 				desc: 'The streaming build system'},
	{name: 'moment', 			desc: 'Parse, validate, manipulate, and display dates'},
	{name: 'browserify', 		desc: 'browser-side require() the node way'},
	{name: 'hapi', 				desc: 'HTTP Server framework'},
	{name: 'q', 				desc: 'A library for promises (CommonJS/Promises/A,B,D)'},
	{name: 'karma', 			desc: 'Spectacular Test Runner for JavaScript.'},
	{name: 'passport', 			desc: 'Simple, unobtrusive authentication for Node.js.'},
	{name: 'chalk', 			desc: 'Terminal string styling done right. Much color.'},
	{name: 'minimist', 			desc: 'Terminal string styling done right. Much color.'},
	{name: 'gulp-concat', 		desc: 'Concatenate files'},
	{name: 'validator', 		desc: 'String validation and sanitization'},
	{name: 'cordova', 			desc: 'Cordova command line interface tool'},
	{name: 'winston', 			desc: 'A multi-transport async logging library for Node.js'},
	{name: 'jshint', 			desc: 'Static analysis tool for JavaScript'},
	{name: 'shelljs', 			desc: 'Portable Unix shell commands for Node.js'},
	{name: 'restify', 			desc: 'REST framework'},
	{name: 'marked', 			desc: 'A markdown parser built for speed'},
	{name: 'morgan', 			desc: 'HTTP request logger middleware for node.js'},
	{name: 'gm', 				desc: 'GraphicsMagick and ImageMagick for node.js'},
	{name: 'express-session', 	desc: 'Simple session middleware for Express'},
	{name: 'phantomjs', 		desc: 'Headless WebKit with JS API'},
	{name: 'through', 			desc: 'simplified stream construction'},
	{name: 'sinon', 			desc: 'JavaScript test spies, stubs and mocks.'},
];

module.exports = items;
